sudo: required
dist: trusty

language: haxe

os:
  - osx

haxe:
  - 4.1.5

script:
  - curl -sSL https://build.haxe.org/builds/haxe/mac/haxe_2021-02-18_fix-macos-10.13_4514864.tar.gz -o haxe.tar.gz
  - tar -xf haxe.tar.gz 
  - cd haxe_20210218195013_4514864
  - ./haxe -x Test