sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.4.4"
  - development

install:
  - if [ "$TRAVIS_HAXE_VERSION" == "development" ]; then
      rm -rf ${HOME}/haxe/*;
      if [ `uname` = "Linux" ]; then
        curl -s -L --retry 3 'https://github.com/HaxeFoundation/haxe/releases/download/4.0.0-preview.3/haxe-4.0.0-preview.3-linux64.tar.gz' | tar -C ${HOME}/haxe -x -z --strip-components=1 -f -;
      else
        curl -s -L --retry 3 'https://github.com/HaxeFoundation/haxe/releases/download/4.0.0-preview.3/haxe-4.0.0-preview.3-osx.tar.gz' | tar -C ${HOME}/haxe -x -z --strip-components=1 -f -;
      fi;
      haxelib setup ${HOME}/haxe/lib;
    fi;
  - echo $(haxe -version)
  - haxelib install travix
  - haxelib run travix install

script:
  - haxe tests.hxml
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  - haxelib run travix java
  - haxelib run travix cpp
  - haxelib run travix cs
  - haxelib run travix php
  #Invalid lua setup on OSX. See https://github.com/back2dos/travix/issues/78
  - if [ `uname` = "Linux" ]; then haxelib run travix lua; fi