sudo: required
dist: trusty

language: haxe

os:
  - osx

haxe:
  - 4.1.5

script:
  - curl -sSL https://build.haxe.org/builds/haxe/mac/haxe_2021-02-19_fix-macos-10.13_d8ab35d.tar.gz -o haxe.tar.gz
  - tar -xf haxe.tar.gz
  - cd haxe_20210219120636_d8ab35d
  - ./haxe -x Test