sudo: required
dist: trusty

language: haxe

os:
  - linux
  # - osx

haxe:
  - development

install:
  - rm -rf ${HOME}/haxe/*
  - if [ `uname` = "Linux" ]; then
      curl -s -L --retry 3 'http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/haxe_2018-01-23_development_ceeba64.tar.gz' | tar -C ${HOME}/haxe -x -z --strip-components=1 -f -;
    else
      curl -s -L --retry 3 'http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/mac/haxe_2018-01-25_development_ceeba64.tar.gz' | tar -C ${HOME}/haxe -x -z --strip-components=1 -f -;
    fi;
  - echo $(haxe -version)
  - haxelib setup ${HOME}/haxe/lib
  - haxelib install travix
  - haxelib run travix install

script:
  - haxe tests.hxml
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  - haxelib run travix java
  - haxelib run travix cpp
  - haxelib run travix cs
  - haxelib run travix php
  #Invalid lua setup on OSX. See https://github.com/back2dos/travix/issues/78
  - if [ `uname` = "Linux" ]; then haxelib run travix lua; fi